# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTimeRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_start', models.DateTimeField()),
                ('datetime_stop', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasktimerange',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Task'),
        ),
    ]
